Fix OpenJPA error in String comparison
OpenJPA does not support "lower(FIELD_NAME) LIKE lower('value')".
According to exception message only "lower(FIELD_NAME) LIKE 'value'" is
supported:

org.apache.openjpa.persistence.ArgumentException: The filter listener
"matches" requires a constant argument.